version: "3"
networks:
  network-healthcheks:
    driver: bridge

volumes:
    db-data:

services:
  {{ DB_HOST }}:
    image: postgres:12
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - network-healthcheks
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    networks:
      - network-healthcheks
    ports:
        - 127.0.0.1:8000:8000
    depends_on:
        - {{ DB_HOST }}
    command: bash -c 'while !</dev/tcp/{{ DB_HOST }}/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
